"""empty message

Revision ID: c698c30731d5
Revises: 3761d306d4ff
Create Date: 2024-03-19 17:28:09.771891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c698c30731d5'
down_revision = '3761d306d4ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ig_access_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('token_expiration', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token_expiration')
        batch_op.drop_column('ig_access_token')

    op.drop_table('images')
    # ### end Alembic commands ###
