"""empty message

Revision ID: dea77e82394f
Revises: 1893b3d20bcf
Create Date: 2024-04-11 12:38:29.533699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea77e82394f'
down_revision = '1893b3d20bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ig_fetched')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ig_fetched', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
