"""empty message

Revision ID: 1893b3d20bcf
Revises: f3baf7d072f3
Create Date: 2024-04-11 12:18:54.158577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1893b3d20bcf'
down_revision = 'f3baf7d072f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_ig_fetch', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_ig_fetch')

    # ### end Alembic commands ###
