"""empty message

Revision ID: 0e5f4f25a326
Revises: a6a4b7315fc5
Create Date: 2024-03-19 17:48:44.655244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e5f4f25a326'
down_revision = 'a6a4b7315fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ig_fetched', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ig_fetched')

    # ### end Alembic commands ###
